# Changes here will be overwritten by Copier
_commit: v6.4.0
_src_path: gh:eccenca/cmem-plugin-template
author_mail: cmempy-developer@eccenca.com
author_name: eccenca GmbH
github_page: https://github.com/eccenca/cmem-plugin-shapes
project_description: Generate SHACL node and property shapes from a data graph
project_slug: shapes
project_type: plugin
pypi: false

